### PR TITLE
Moved to N-API

### PR DESCRIPTION
**Pull request by danielgindi**

### CODE REVIEW

**Comment by danielgindi** [comment]
@simonbuchan ?

**Comment by danielgindi** [comment]
Yes, NAPI was experimental but now it is the way to be ABI compatible with different node versions, which is a major upside.

You could, by the way, edit the PR. As it is on a fork from your repo - you should have permissions to push to my branch. I have automatic default formatting with MSVC (which is a much cleaner style), but it's your repo and I'll respect your preferences.

**Comment by simonbuchan** [comment]
Merged with a decent amount of refactoring. Take a look at fd0332bc8d0bea189ef4017c09471ebf2f1bcd65 to see the changes I made past this, or d1fac1b...fd0332b for the combined changes.

**Comment by simonbuchan** [comment]
Thanks for putting the effort in, despite the changes I ended up making, having the new way to do things right there was super helpful!

**Comment by danielgindi** [comment]
Amazing :-)

I have a few notes/questions there:
1. Why did you downgrade from c++ `Napi::Object` to C `napi_value` (i.e in `Init`)?
2. I'm always doing `auto const &` there, as to not assume the underlying type. It's a matter of convention/style I guess. I don't really mind :-)
3. Sorry for missing those utf16-arrays...
4. I created that `throw_win32` mainly based on looking at node's source code. This is how they generate their errors, same source for formatting the native error message, same structure, and most importantly `ThrowAsJavaScriptException`. If course `ThrowAsJavaScriptException` itself can throw, especially if not on a node.js-context v8 thread, but you get the benefit of being able to catch in JS side.

**Comment by simonbuchan** [comment]
1. Not really sure actually - I was investigating `NODE_API_MODULE()` (e.g. it's usage of `HandleScope`) and found the example code on the N-API docs using `NAPI_MODULE`. Not much difference for code this simple, I guess, other than `NODE_API_MODULE()` probably wraps the code in C++ exception handling.
2. \*waggles hand\*. Technically a little slower in that it has to dereference the `&` as well, and you now have aliasing to consider in the back of your mind, but mainly the issue is it implies that the value has a heavy copy, which can possibly confuse things. Certainly it's nicer to see `void foo(Env env, Value value)` than `void foo(Env const& env, Value const& value)`!
3. Hah, this was NAN being garbage, and my tests covering everything but those methods, so don't worry about it!
4. That's the not using C++ exceptions pattern but it seems to be pretty reasonable a default to throw in C++. Ends up being the same thing, `Napi` will wrap your code in a [`try ... catch (const Error& e) { e.ThrowAsJavaScriptError(); }`](https://github.com/nodejs/node-addon-api/blob/fa49d6841616c12d2602a5454599fc6e8783d0cc/napi-inl.h#L118-L123) unless you disable it. The code changes I made inside were just because I noticed it was using the ANSI version of `FormatMessage`, meaning it was using the active system code page (a system-wide setting) then reading it as UTF-8. That's not so much of a problem nowadays, as windows 10 changed the system default active code page to `UTF-8`, but on pre-10 windows or if it was changed by someone for compatibility reasons that would mangle the output here. I should probably submit this as a patch upstream, though it's hard to write a test depending on a system-level setting :)

**Comment by danielgindi** [comment]
Well you could change the default code page for that easily:
https://github.com/simonbuchan/native-reg/pull/1/commits/9e4773848549e5e9f6c5161fcd2a9b916d9360cd#diff-c2c60698009e86a2397f830b54262ebeR33

**Comment by simonbuchan** [comment]
Nope: LANGID != ACP - doing that lets you force the text language to en-US, for example, which is much less likely to have non-ASCII characters, but not to change the encoding of the text to UTF-8. I took a look around, but there didn't seem to be a way to change the ACP on a per-process or call level.

**Comment by danielgindi** [comment]
After receiving a single-byte string in any codepage, we can use `MultiByteToWideChar`, and take a Node string from the UTF16 representation, or convert it then back to UTF8 with `WideCharToMultiByte` and get a UTF8 string.
But that's too much work.

**Comment by simonbuchan** [comment]
Don't be too hard on them, Microsoft actually supported Unicode as UCS-2 from '93 with NT. UTF-8 was only invented that year, so I don't blame them for not initially including it! They had been pushing against allowing UTF for ACP for a long time as it meant literally every Windows API with an ANSI variant (e.g. every API that took text!) would have to be verified and updated as one UTF-16 character can be more than two UTF-8 characters, unlike every other code page. I do wish they allowed setting ACP for a process or thread though, as it would mean it's much easier than doing UTF-8/16 conversions everywhere yourself.

Note that JS is UTF-16 internally as well, so it actually works out very nicely to stick to it.

**Pull request merged**
